La paqueteria de numpy es una de as herramientas ma populares dentro de la ciencia de datos con python

In [2]:
import numpy as np

In [10]:
#Creando un Array - numpyarray
valoraciones = np.array([[8,7,8,5], [2,6,8,1], [8,8,9,5]])
valoraciones
#Nos presentara una matriz con dos ejes.
#Eje | donde tenemos 4 columnas y --> horizontal donde tenemos 3 filas

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [4]:
#Accediendo a la dimension 0 (de los horizontes) y a la simension 1 (de las filas)
valoraciones[1][1]

np.int64(6)

In [5]:
#Alternativo
valoraciones[0,1]

np.int64(7)

In [6]:
valoraciones2 = np.array([[[8, 7, 8, 5], [2, 6, 8, 1], [8, 8, 9, 5]],
                          [[1, 3, 5, 7], [9, 2, 4, 6], [0, 1, 2, 3]],
                          [[0, 1, 2, 7], [4, 1, 2, 6], [6, 7, 5, 1]]])
valoraciones2

array([[[8, 7, 8, 5],
        [2, 6, 8, 1],
        [8, 8, 9, 5]],

       [[1, 3, 5, 7],
        [9, 2, 4, 6],
        [0, 1, 2, 3]],

       [[0, 1, 2, 7],
        [4, 1, 2, 6],
        [6, 7, 5, 1]]])

In [7]:
valoraciones2[0,2,2]

np.int64(9)

In [8]:
#Crear arrays vacios
np.zeros ((3,2,4))
#3 = Cantidad de contenedores
#2 = numero de horizontales
#4 = numero de columnas

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
#Operaciones entre arrays de mismo tamaño
#Los valores de los contenedores se estan sumando en  +1
valoraciones2 + np.ones((3,3,4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  7.,  9.,  2.],
        [ 9.,  9., 10.,  6.]],

       [[ 2.,  4.,  6.,  8.],
        [10.,  3.,  5.,  7.],
        [ 1.,  2.,  3.,  4.]],

       [[ 1.,  2.,  3.,  8.],
        [ 5.,  2.,  3.,  7.],
        [ 7.,  8.,  6.,  2.]]])

In [ ]:
#Aplicamos la media a todos los valores de los arrays
np.mean(valoraciones2)

np.float64(4.444444444444445)

In [20]:
#Calculamos la media de seleccionando su dimension
np.mean(valoraciones2,axis=2)

array([[7.  , 4.25, 7.5 ],
       [4.  , 5.25, 1.5 ],
       [2.5 , 3.25, 4.75]])

In [21]:
#Nos permite convertir una lista  a las dimensiones que nosotros queramos
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12], (3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
np.median(df["Columna1"])

In [ ]:
#Nos permite crear numeros aleatorios
np.random.rand(2,2)

array([[0.19514849, 0.9223037 ],
       [0.22781185, 0.14329847]])